import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getData } from '../lib/api'
import { IPost } from '../interfaces/IPost'
import Board from '../components/Board/Board'

const Home: NextPage<{ posts: IPost[] }> = ({ posts }) => {

  return (
    <div className={styles.container}>
      <Head>
        <title>Task-4 | a-bodrova</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Posts</h1>
        <Board cards={Array.from(posts)} />
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  const posts: IPost[] = await (await getData('/api/posts')).data;

  return {
    props: { posts },
  }
}

export default Home
